### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by arnaldojr** [lucasrabd/WellDoneABX#2]
1 - prestar atenção na análise e não confiar tanto na análise que a empresa fez... 
2 - sobe o csv para o repositório
3 - cria um txt com descritivo das colunas.
4 - cria o notebook para iniciar a análise.

**Comment by lucasrabd** [comment]
- [  ✔] 1 - prestar atenção na análise e não confiar tanto na análise que a empresa fez... (mudada a estratégia pois analistas da empresa não são confiaveis. 
- [  ✔] 2 - sobe o csv para o repositório (CSV comitado para repositório)
- [  ✔] 3 - cria um txt com descritivo das colunas. (Txt criado e sendo comitado)
- [  ✔ 4 - cria o notebook para iniciar a análise.  (Será adicionado mais tarde, assim que for adicionado irei commitar)
